<a href="https://colab.research.google.com/github/Sonaxy/Python-Programming-Basics/blob/main/7_Python_101_Python_Libraries_for_Data_Analysis_Numpy_Skeleton.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. NUMPY BASICS

In [1]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax
import numpy as np

# Let's define a one-dimensional array
my_list = [10, 20, 50, 60, 70]
my_list

In [ ]:
# Let's create a numpy array from the list "my_list"
arr1 = np.array(my_list)
arr1

array([10, 20, 50, 60, 70])

In [ ]:
# Multi-dimensional (Matrix definition)
mat1 = np.array([[5, 8], [9, 13]])
mat1

array([[ 5,  8],
       [ 9, 13]])

**MINI CHALLENGE #1:**
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7]
[20 5 6 9]]
```

In [ ]:
mat2 = np.array([[4, 6, 8, 7], [20, 5, 6, 9]])
mat2

array([[ 4,  6,  8,  7],
       [20,  5,  6,  9]])

# 2. BUILT-IN METHODS AND FUNCTIONS

In [ ]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(15)
x

array([0.41307515, 0.31259328, 0.54467214, 0.00888341, 0.2061673 ,
       0.71220318, 0.95435937, 0.52569771, 0.51041666, 0.22742082,
       0.88737715, 0.990624  , 0.40172669, 0.12912317, 0.51571652])

In [ ]:
# you can create a matrix of random number as well
x = np.random.rand(5, 5)
x

array([[0.54817221, 0.66934088, 0.85581152, 0.89247493, 0.17784313],
       [0.65942113, 0.90715114, 0.85886832, 0.3667819 , 0.39482189],
       [0.85847919, 0.5029293 , 0.89211787, 0.02158242, 0.9711555 ],
       [0.6995863 , 0.03493066, 0.70776582, 0.04276333, 0.7191386 ],
       [0.05105125, 0.01533429, 0.95546325, 0.81365883, 0.89896682]])

In [ ]:
# "randn()" normal distribution between 0 and 1
x = np.random.randn(10)
x

array([ 0.64513915,  0.95458492, -0.566712  , -1.54310557,  0.29284571,
        0.86203839,  0.35546594,  0.04027088,  0.66838357,  0.74410282])

In [ ]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1,10)
x

4

In [ ]:
# "randint" can be used to generate a certain number of random itegers as follows
x = np.random.randint(1,10, 5)
x

array([2, 2, 3, 9, 9])

In [ ]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1, 50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
# Create an evenly spaced values with a step of 5
x = np.arange(1, 50, 5)
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [ ]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(10)
x

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
# Array of ones
x = np.ones(10)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# Matrices of ones
x = np.ones((5, 5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Array of zeros
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**MINI CHALLENGE #2:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [ ]:
max_no = int(input("Enter the upper bound for the range: "))

my_list = np.random.randint(0, max_no, 20)
my_list

Enter the upper bound for the range: 50


array([37, 10, 17,  2,  3, 16, 48, 13,  8, 46,  7, 41, 13, 22, 37,  6, 33,
       12, 16, 36])

# 3. SHAPE, LENGTH, TYPE, RESHAPE, AND MAX/MIN VALUES

In [ ]:
# Let's define a one-dimensional array
my_list = [-30, 4, 50, 60, 29, 15, 22, 90]
my_list

x = np.array(my_list)
x

array([-30,   4,  50,  60,  29,  15,  22,  90])

In [ ]:
# Get Length of a numpy array
len(x)

8

In [ ]:
# Get shape
x.shape

(8,)

In [ ]:
# Obtain the datatype
x.dtype

dtype('int64')

In [ ]:
# Reshape 1D array into a matrix
z = x.reshape(2, 4)
z

array([[-30,   4,  50,  60],
       [ 29,  15,  22,  90]])

In [ ]:
# Obtain the maximum element (value)
x.max()

90

In [ ]:
# Obtain the minimum element (value)
x.min()

-30

In [ ]:
# Obtain the location of the max element
x.argmax()

7

In [ ]:
# Obtain the location of the min element
x.argmin()

0

**MINI CHALLENGE #3:**
- **Write a code that creates a 4x5 array inwhich numbers range between 300 and 500 such that the difference between elements is 10**

In [ ]:
# creating an array of numbers ranging between 300 and 500 with a difference of 10 between the elements
x = np.arange(300, 500, 10)
x

# checking the shape of x
x.shape

# reshaping the 1D array to a 4X5 array
z = x.reshape(4,5)
z

(20,)

**MINI CHALLENGE #4:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values**

In [ ]:
# create an array of 400 elements that ranges from -1000 to 1000
x = np.random.randint(-1000, 1000, (20,20))
x

# verifying the shape of x
x.shape

# finding the maximum value
x.max()

# finding the minimum value
x.min()

# finding the mean values
x.mean()

(20, 20)

# 4. MATHEMATICAL OPERATIONS

In [ ]:
# np.arange() returns an evenly spaced values within a given interval
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
y = np.arange(1,10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Add 2 numpy arrays together
z = x+y
z

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# Squared of a numpy array
squared = x**2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
# Squareroot of a numpy array
sqrts = np.sqrt(squared)
sqrts

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

**MINI CHALLENGE #5:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```

In [ ]:
X = np.array([3, 20, 30])
Y = np.array([4, 6, 7])
distance = np.sqrt(X**2 + Y**2)
distance

array([ 5.        , 20.88061302, 30.8058436 ])

# 5. SLICING AND INDEXING

In [2]:
x = np.array([20, 40, 50, 21, 15])

In [5]:
# Access specific index from the numpy array
print(x[0])
print(x[3])

20
21


In [6]:
# Starting from the first index 0 up until and NOT inlcluding the last element
x[0:3]

array([20, 40, 50])

In [7]:
# Broadcasting, altering several values in a numpy array at once
x[0:2] = 10
x

array([10, 10, 50, 21, 15])

In [8]:
# Let's define a two dimensional numpy array
mat1 = np.random.randint(1, 10, (5, 5))
mat1

array([[7, 9, 3, 2, 7],
       [4, 6, 6, 6, 2],
       [4, 3, 6, 9, 4],
       [6, 1, 2, 9, 8],
       [6, 3, 3, 7, 6]])

In [9]:
# Get a row from a mtrix
mat1[2]

array([4, 3, 6, 9, 4])

In [10]:
# Get one element
mat1[2][3]

9

In [16]:
# Get subset of the matrix
mat2 = mat1[:3]
mat2

array([[7, 9, 3, 2, 7],
       [4, 6, 6, 6, 2],
       [4, 3, 6, 9, 4]])

In [14]:
mat3 = mat1[:,2:]
mat3

array([[3, 2, 7],
       [6, 6, 2],
       [6, 9, 4],
       [2, 9, 8],
       [3, 7, 6]])

In [17]:
# All rows and all columns - another approach
mat1[:, :]

array([[7, 9, 3, 2, 7],
       [4, 6, 6, 6, 2],
       [4, 3, 6, 9, 4],
       [6, 1, 2, 9, 8],
       [6, 3, 3, 7, 6]])

**MINI CHALLENGE #6:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [26]:
# Create a matrix
X = np.array([[2, 30 ,20 ,-2 ,-4],
    [3 ,4  ,40 ,-3 ,-2],
    [-3 ,4 ,-6 ,90 ,10],
    [25 ,45 ,34 ,22 ,12],
    [13 ,24 ,22 ,32 ,37]])
print(X)

# Replace the last row with -1
X[4] = -1

# Print the new matrix
print("\n")
print(X)

# Multiply the 2x2 matrix in the upper right corner by 2
X[0:2, 3:] = X[0:2, 3:] * 2

# Print the new matrix
print("\n")
print(X)

[[ 2 30 20 -2 -4]
 [ 3  4 40 -3 -2]
 [-3  4 -6 90 10]
 [25 45 34 22 12]
 [13 24 22 32 37]]


[[ 2 30 20 -2 -4]
 [ 3  4 40 -3 -2]
 [-3  4 -6 90 10]
 [25 45 34 22 12]
 [-1 -1 -1 -1 -1]]


[[ 2 30 20 -4 -8]
 [ 3  4 40 -6 -4]
 [-3  4 -6 90 10]
 [25 45 34 22 12]
 [-1 -1 -1 -1 -1]]


# 6. ELEMENTS SELECTION (CONDITIONAL)

In [27]:
mat3 = np.random.randint(1, 10, (5,5))
mat3

array([[3, 5, 3, 7, 2],
       [4, 4, 6, 8, 6],
       [3, 3, 1, 4, 7],
       [6, 8, 8, 4, 2],
       [7, 1, 3, 6, 7]])

In [28]:
mat4 = mat3[ mat3 > 3]
mat4

array([5, 7, 4, 4, 6, 8, 6, 4, 7, 6, 8, 8, 4, 7, 6, 7])

In [30]:
mat4 = mat3[ mat3 % 2 == 0]
mat4

array([2, 4, 4, 6, 8, 6, 4, 6, 8, 8, 4, 2, 6])

**MINI CHALLENGE #7:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [33]:
# Create a matrix
X = np.array([[2, 30 ,20 ,-2 ,-4],
    [3 ,4  ,40 ,-3 ,-2],
    [-3 ,4 ,-6 ,90 ,10],
    [25 ,45 ,34 ,22 ,12],
    [13 ,24 ,22 ,32 ,37]])
print(X)

# Replace negative elements by 0
X [ X < 0] = 0

# Replace odd elements with 25
X [ X % 2 != 0] = 25

# Print the new matrix
print("\n")
print(X)

[[ 2 30 20 -2 -4]
 [ 3  4 40 -3 -2]
 [-3  4 -6 90 10]
 [25 45 34 22 12]
 [13 24 22 32 37]]


[[ 2 30 20  0  0]
 [25  4 40  0  0]
 [ 0  4  0 90 10]
 [25 25 34 22 12]
 [25 24 22 32 25]]


# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

**MINI CHALLENGE #1 SOLUTION:**
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7]
[20 5 6 9]]
```

In [ ]:
x = np.array([[[4, 6, 8, 7] , [20, 5, 6, 9]]])
x

**MINI CHALLENGE #2 SOLUTION:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [ ]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 20)
x

**MINI CHALLENGE #3 SOLUTION:**
- **Write a code that creates a 4x5 array inwhich numbers ranging between 300 and 500 such that the difference between elements is 10**

In [ ]:
x = np.arange(300, 500, 10)
x.shape

In [ ]:
x = x.reshape(4, 5)
print(x)

**MINI CHALLENGE #4 SOLUTION:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values**

In [ ]:
x = np.random.randint(-1000, 1000, (20, 20))
print(x)
print('The maximum value is: {} and the minimum value is:{}'.format(x.min(), x.max()))

**MINI CHALLENGE #5 SOLUTION:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```




In [ ]:
X = np.array([3, 20, 30])
Y = np.array([4, 6, 7])
Z = np.sqrt(X**2 + Y**2)
Z

**MINI CHALLENGE #6 SOLUTION:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [ ]:
X[4] = 0
X

In [ ]:
X[:2, 3:]  = X[:2, 3:] * 2

In [ ]:
X

**MINI CHALLENGE #7 SOLUTION:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X%2==1] = 25
X[X<0] = 0
X